version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: plantondemand/pod-shop-vue:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8080:8080"
    networks:
      - webnet
  flask:
    image: plantondemand/pod-shop-flask:latest
    ports:
      - "5000:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
networks:
  webnet: