branch-defaults:
  default:
    environment: lge-elb
environment-defaults:
  lge-elb:
    branch: null
    repository: null
global:
  application_name: lge-test-ElasticBeanstalkApp-16ABSO492ASST
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Python 2.7 running
    on 64bit Amazon Linux/2.8.0
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
